server:
  port: 8762

spring:
  application:
    name: service-goods
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


